# Generated by Django 2.2.24 on 2023-07-12 21:27

from django.db import migrations
import phonenumbers
import phonenumber_field.modelfields


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_phonenumber,
                phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.save()
            continue
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20230712_2329'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone),
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Нормализованный номер владельца'),
        ),
    ]
